### ISSUE TITLE
Your key needs to be better integrated into the WoT/otherwise verifiable

### ISSUE THREAD

**Issue by petertodd** [rnicoll/python-altcoinlib#1]
0x9142E5F7E533CE3B has just one sig; where would I know to get a correct copy of it?

Having said that +∞ for signing the code in the first place; I'm mostly opening this issue to give you kudo's for that. :)

**Comment by rnicoll** [comment]
https://github.com/dogecoin/dogecoin/blob/master/contrib/gitian-downloader/rnicoll-key.pgp is probably a good stable location. Feel free to ping me on reddit (same username) to check fingerprint.

However, yes, aware I need signatures, but there's not a lot going on in the way of key signing where I am currently. Relocating in March to near London, that should help!

**Comment by petertodd** [comment]
Sounds good to me.

re: London, awesome! I'm relatively often there; I'll have to say hi next time.
